server:
  port: 8080
spring:
  application:
    name: moviefun
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    jmx-enabled: false
    username: root
    password: test

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp